---

site_name: ce-vm

repo_url: https://github.com/codeenigma/ce-vm-docs

theme: readthedocs

pages:
  - About: index.md
  - Getting started:
    - Installation: get-started/install.md
    - Usage: get-started/usage.md
  - Customisation:
    - Configuration: config/config.md
    - Ansible customization: config/ansible.md
  - Stack details:
    - Overview: stack/overview.md
    - Services:
      - Syslog: stack/services/log.md
      - Dashboard: stack/services/dashboard.md
      - NGINX: stack/services/nginx.md
      - PHP: stack/services/php.md
      - Solr: stack/services/solr.md
  - Tips & recipes:
      - Wrapper scripts: tips/scripts.yml
      - SSH: tips/ssh.yml
  - Topics:
      - Upgrades: topics/upgrades.md
      - Shared mounts: topics/shared-mounts.md
      - Security: topics/security.md
      - Networking: topics/networking.md
      - Email: topics/postfix.md